### ISSUE TITLE
Dto -> DTO 변경 건의

### ISSUE THREAD

**Issue by JaeSang1998** [Project-Donggle/donggle-back#13]
DTO 는 Data Transfer Object 의 줄임말이니 대문자로 작성하는게 어떨까요??

**Comment by shownprove** [comment]
음... nest 명명법? 철학? 의 차원인건지 우연인지 몰라도, nest로 빌드한 코드들 보면 DTO라고 표기한 코드가 하나도 없더라구요. 적어도 제가 본 것들은 다 그랬어서.. 뭔가 이유가 있을듯하여 저는 반대입니다!

**Comment by shownprove** [comment]
반영완료
